version: "3.7"
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=airflow
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    webserver:
        image: puckel/docker-airflow:latest
        container_name: airflow
        restart: always
        depends_on:
            - postgres
            - scheduler
        command: bash -c "airflow initdb && airflow webserver"
        env_file:
            - .env
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./test:/usr/local/airflow/test
            - ./plugins:/usr/local/airflow/plugins
            - ./logs:/usr/local/airflow/logs
            - ./data:/usr/local/airflow/data/
            - ./scripts:/usr/local/airflow/scripts
            - ./airflow.cfg:/usr/local/airflow/airflow.cfg
            # - ~/.aws:/usr/local/airflow/.aws
        ports:
            - "8080:8080"
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    scheduler:
        image: puckel/docker-airflow:latest
        restart: always
        depends_on:
            - postgres
        command: scheduler
        env_file:
            - .env
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
            - ./data:/usr/local/airflow/data/
            - ./airflow.cfg:/usr/local/airflow/airflow.cfg
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-scheduler.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3    